// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nuclep.GestaoQualidade.SqlServer.Contexts;

#nullable disable

namespace Nuclep.GestaoQualidade.SqlServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241204170757_SatisfacaoUsuario")]
    partial class SatisfacaoUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AcaoCorrecaoAvaliadaEficaz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TotalAbertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalFechamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalTratamentoEficaz")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int")
                        .HasColumnName("Trimestre");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_AcaoCorrecaoAvaliadaEficaz", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AcaoCorrecaoAvaliadaEficazMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_AcaoCorrecaoAvaliadaEficazMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AderenciaProgramacaoMensal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<decimal?>("AtividadesCanceladas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AtividadesRealizadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TotalAtividadesProgramadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_AderenciaProgramacaoMensal", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AderenciaProgramacaoMensalMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Meta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_AderenciaProgramacaoMensalMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AutoavaliacaoGerencialSGQ", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Realizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_AutoavaliacaoGerencialSGQ", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AutoavaliacaoGerencialSGQMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_AutoavaliacaoGerencialSGQMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoEtapasPACDentroPrazo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("PACPrazo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalPACAberto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_CumprimentoEtapasPACDentroPrazo", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoEtapasPACDentroPrazoMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Meta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_CumprimentoEtapasPACDentroPrazoMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoVerbaDestinadaPATMME", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Realizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int")
                        .HasColumnName("Semestre");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_CumprimentoVerbaDestinadaPATMME", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoVerbaDestinadaPATMMEMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_CumprimentoVerbaDestinadaPATMMEMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DefeitoSoldagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<long>("LocalidadeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TotalComprimentoSoldadoInspecionado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDefeitosSoldaEncontradosEnsaiadosVolumetricos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadeId");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_DefeitoSoldagem", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DefeitoSoldagemMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_DefeitoSoldagemMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DuracaoProcessoLicitacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiasCorridos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int")
                        .HasColumnName("Trimestre");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_DuracaoProcessoLicitacao", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DuracaoProcessoLicitacaoMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_DuracaoProcessoLicitacaoMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.EficaciaTreinamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Realizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int")
                        .HasColumnName("Semestre");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_EficaciaTreinamento", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.EficaciaTreinamentoMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_EficaciaTreinamentoMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.FaturamentoRealizado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("PrevistoJaneiroAnoCorrente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SomatorioFaturamentoRealizadoTrimestre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int")
                        .HasColumnName("Trimestre");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_FaturamentoRealizado", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.FaturamentoRealizadoMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_FaturamentoRealizadoMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.OcupacaoMaoObra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TempoDisponivelFabril")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TempoEfetivoFabril")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_OcupacaoMaoObra", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.OcupacaoMaoObraMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_OcupacaoMaoObraMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.ProdutividadeMaoObra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TempoDisponivelTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TempoTotalFaturavel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_ProdutividadeMaoObra", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.ProdutividadeMaoObraMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_ProdutividadeMaoObraMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RejeicaoMateriais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TotalCTIsFinalizados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCTIsRejeitados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int")
                        .HasColumnName("Trimestre");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_RejeicaoMateriais", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RejeicaoMateriaisMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_RejeicaoMateriaisMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RespostaAreasRiscosPrazoOriginal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Realizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int")
                        .HasColumnName("Trimestre");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_RespostaAreasRiscosPrazoOriginal", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RespostaAreasRiscosPrazoOriginalMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_RespostaAreasRiscosPrazoOriginalMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoClientes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Realizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_SatisfacaoClientes", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoClientesMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_SatisfacaoClientesMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<decimal?>("Atividade1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Atividade2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ind_SatisfacaoUsuario", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoUsuarioMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId")
                        .IsUnique();

                    b.ToTable("Ind_SatisfacaoUsuarioMeta", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Localidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCadastroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Sys_Localidade", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.LogCrud", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataHoraCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdReferencia")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<long>("LogTabelaId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogTabelaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogTipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sys_LogCrud", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.LogTabela", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sys_LogTabela", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdUsuarioCadastro")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAcaoCorrecaoAvaliadaEficaz")
                        .HasColumnType("bit")
                        .HasColumnName("IsAcaoCorrecaoAvaliadaEficaz");

                    b.Property<bool>("IsAcaoDentroPrazo")
                        .HasColumnType("bit")
                        .HasColumnName("IsAcaoDentroPrazo");

                    b.Property<bool>("IsAderenciaProgramacaoMensal")
                        .HasColumnType("bit")
                        .HasColumnName("IsAderenciaProgramacaoMensal");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoavaliacaoGerencialSGQ")
                        .HasColumnType("bit")
                        .HasColumnName("IsAutoavaliacaoGerencialSGQ");

                    b.Property<bool>("IsCapacitacaoAreaContratos")
                        .HasColumnType("bit")
                        .HasColumnName("IsCapacitacaoAreaContratos");

                    b.Property<bool>("IsCondensador")
                        .HasColumnType("bit")
                        .HasColumnName("IsCondensador");

                    b.Property<bool>("IsConfirmacaoNaoInformado")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCumprimentoEtapasPACDentroPrazo")
                        .HasColumnType("bit")
                        .HasColumnName("IsCumprimentoEtapasPACDentroPrazo");

                    b.Property<bool>("IsCumprimentoVerbaDestinadaPATMME")
                        .HasColumnType("bit")
                        .HasColumnName("IsCumprimentoVerbaDestinadaPATMME");

                    b.Property<bool>("IsDuracaoProcessoLicitacao")
                        .HasColumnType("bit")
                        .HasColumnName("IsDuracaoProcessoLicitacao");

                    b.Property<bool>("IsEficaciaTreinamento")
                        .HasColumnType("bit")
                        .HasColumnName("IsEficaciaTreinamento");

                    b.Property<bool>("IsEventosAtraso")
                        .HasColumnType("bit")
                        .HasColumnName("IsEventosAtraso");

                    b.Property<bool>("IsFaturamentoRealizado")
                        .HasColumnType("bit")
                        .HasColumnName("IsFaturamentoRealizado");

                    b.Property<bool>("IsGestaoProcessosPessoasPrevistoPAT")
                        .HasColumnType("bit")
                        .HasColumnName("IsGestaoProcessosPessoasPrevistoPAT");

                    b.Property<bool>("IsItensCadastradosMais15Dias")
                        .HasColumnType("bit")
                        .HasColumnName("IsItensCadastradosMais15Dias");

                    b.Property<bool>("IsLocalidadeAramar")
                        .HasColumnType("bit")
                        .HasColumnName("IsLocalidadeAramar");

                    b.Property<bool>("IsLocalidadeItaguai")
                        .HasColumnType("bit")
                        .HasColumnName("IsLocalidadeItaguai");

                    b.Property<bool>("IsNivelServicoAtendimento")
                        .HasColumnType("bit")
                        .HasColumnName("IsNivelServicoAtendimento");

                    b.Property<bool>("IsOcupacaoMaoObra")
                        .HasColumnType("bit")
                        .HasColumnName("IsOcupacaoMaoObra");

                    b.Property<bool>("IsProdutividadeMaoObra")
                        .HasColumnType("bit")
                        .HasColumnName("IsProdutividadeMaoObra");

                    b.Property<bool>("IsReducaoRNC")
                        .HasColumnType("bit")
                        .HasColumnName("IsReducaoRNC");

                    b.Property<bool>("IsRejeicaoMateriais")
                        .HasColumnType("bit")
                        .HasColumnName("IsRejeicaoMateriais");

                    b.Property<bool>("IsRespostaAreasPrazoOriginal")
                        .HasColumnType("bit")
                        .HasColumnName("IsRespostaAreasPrazoOriginal");

                    b.Property<bool>("IsRespostaAreasRiscosPrazoOriginal")
                        .HasColumnType("bit")
                        .HasColumnName("IsRespostaAreasRiscosPrazoOriginal");

                    b.Property<bool>("IsRetrabalhoDocumentos")
                        .HasColumnType("bit")
                        .HasColumnName("IsRetrabalhoDocumentos");

                    b.Property<bool>("IsSatisfacaoClientes")
                        .HasColumnType("bit")
                        .HasColumnName("IsSatisfacaoClientes");

                    b.Property<bool>("IsSatisfacaoClientesAreaResponsavel")
                        .HasColumnType("bit")
                        .HasColumnName("IsSatisfacaoClientesAreaResponsavel");

                    b.Property<bool>("IsSatisfacaoUsuario")
                        .HasColumnType("bit")
                        .HasColumnName("IsSatisfacaoUsuario");

                    b.Property<bool>("IsTaxaConformidadeDocumentosQualidade")
                        .HasColumnType("bit")
                        .HasColumnName("IsTaxaConformidadeDocumentosQualidade");

                    b.Property<bool>("IsTempoManutencaoCorretivaEquipamentoProgramado")
                        .HasColumnType("bit")
                        .HasColumnName("IsTempoManutencaoCorretivaEquipamentoProgramado");

                    b.Property<bool>("IsTempoMedioInspecaoRecebimentoMateriais")
                        .HasColumnType("bit")
                        .HasColumnName("IsTempoMedioInspecaoRecebimentoMateriais");

                    b.Property<bool>("IsTempoMedioSolucao")
                        .HasColumnType("bit")
                        .HasColumnName("IsTempoMedioSolucao");

                    b.Property<bool>("IsTempoReparoEquipamentosProgramadosObras")
                        .HasColumnType("bit")
                        .HasColumnName("IsTempoReparoEquipamentosProgramadosObras");

                    b.Property<bool>("IsVPR")
                        .HasColumnType("bit")
                        .HasColumnName("IsVPR");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilSistema")
                        .HasColumnType("int")
                        .HasColumnName("PerfilSistema");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("Sys_Usuario", (string)null);
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AcaoCorrecaoAvaliadaEficaz", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AcaoCorrecaoAvaliadaEficazMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AcaoCorrecaoAvaliadaEficazMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AderenciaProgramacaoMensal", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AderenciaProgramacaoMensalMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AderenciaProgramacaoMensalMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AutoavaliacaoGerencialSGQ", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AutoavaliacaoGerencialSGQMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.AutoavaliacaoGerencialSGQMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoEtapasPACDentroPrazo", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoEtapasPACDentroPrazoMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoEtapasPACDentroPrazoMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoVerbaDestinadaPATMME", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoVerbaDestinadaPATMMEMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.CumprimentoVerbaDestinadaPATMMEMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DefeitoSoldagem", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidade");

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DefeitoSoldagemMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DefeitoSoldagemMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DuracaoProcessoLicitacao", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DuracaoProcessoLicitacaoMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.DuracaoProcessoLicitacaoMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.EficaciaTreinamento", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.EficaciaTreinamentoMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.EficaciaTreinamentoMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.FaturamentoRealizado", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.FaturamentoRealizadoMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.FaturamentoRealizadoMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.OcupacaoMaoObra", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.OcupacaoMaoObraMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.OcupacaoMaoObraMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.ProdutividadeMaoObra", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.ProdutividadeMaoObraMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.ProdutividadeMaoObraMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RejeicaoMateriais", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RejeicaoMateriaisMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RejeicaoMateriaisMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RespostaAreasRiscosPrazoOriginal", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RespostaAreasRiscosPrazoOriginalMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.RespostaAreasRiscosPrazoOriginalMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoClientes", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoClientesMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoClientesMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoUsuario", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoUsuarioMeta", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithOne()
                        .HasForeignKey("Nuclep.GestaoQualidade.Domain.Models.Indicadores.SatisfacaoUsuarioMeta", "UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Localidade", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.LogCrud", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Nuclep.GestaoQualidade.Domain.Models.Usuario", b =>
                {
                    b.HasOne("Nuclep.GestaoQualidade.Domain.Models.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro");

                    b.Navigation("UsuarioCadastro");
                });
#pragma warning restore 612, 618
        }
    }
}
